### ISSUE TITLE
[UX Design] Complete mockups of user flow

### ISSUE THREAD

**Issue by abarciauskas-bgse** [codefordc/cfsa-referral#20]
Complete mockups of user flow. Should probably be "mobile first" since case workers use tablets.

These have been started [in this slide from the hackathon](https://docs.google.com/presentation/d/1oXRAdxm1okFz6p6vWFDv_-YOEyNqc3WUp-LFHHUPXwI/edit#slide=id.g200c066211_0_25)

**Comment by jsya** [comment]
Please use this skeleton wireframe. Save a copy under a new file name

https://drive.google.com/open?id=0B8aPOKn3WbJDRklzTGhzNHdVMTQ

**Comment by jenboyd** [comment]
@jsya

**Comment by jenboyd** [comment]
@jsya Making some updates to the wireframes based on our conversation and the guidelines linked in Issue #22

**Comment by jenboyd** [comment]
See some potential design ideas in the updates to the wireframes below:

[https://drive.google.com/open?id=0B_6rWAyQXTb1b2N5dlV0M2JhaDg](url)

**Comment by jsya** [comment]
Thanks Jen! We're at Code for DC tonight and I'll take a look at your wire frames

**Comment by abarciauskas-bgse** [comment]
https://invis.io/2AE4CENGY
