### ISSUE TITLE
[Frontend] Update the favicon and title to be more DC themed

### ISSUE THREAD

**Issue by mkalish** [codefordc/cfsa-referral#23]

**Comment by srijakumar** [comment]
Working on it!

**Comment by mkalish** [comment]
This includes changing the favicon to use the DC government logo found here http://rui.dc.gov/style-guide/ and updating the title to be CFSA Referral

**Comment by BtheGit** [comment]
#38 Only half the task. Recommend sticking Helmet in their at some point.

**Comment by abarciauskas-bgse** [comment]
Completed
