### ISSUE TITLE
[Frontend] First page should "Login"

### ISSUE THREAD

**Issue by abarciauskas-bgse** [codefordc/cfsa-referral#27]
Implement login screen. Given this is a prototype, all non-empty login strings will be accepted.

Implement basic form as seen in the first screen below, no styling required:
![preview 2](https://user-images.githubusercontent.com/15016780/31866742-2fef0a5c-b752-11e7-94f5-5665f0b43f05.png)

**Comment by BtheGit** [comment]
I'm gonna take a crack at this right now if that's ok.

**Comment by BtheGit** [comment]
#28

**Comment by BtheGit** [comment]
I made a PR for the Login page (and a few other minor changes that were needed, apologies for the overloading) #28

**Comment by abarciauskas-bgse** [comment]
@BtheGit already did work on this, just assigning to @mkalish since he mentioned making the landing page the login page. (Right now you have to navigate to /Login)

**Comment by BtheGit** [comment]
My current PR #36 does this as it sets home (ie Question) as a PrivateRoute which redirects to Login if needed.

**Comment by abarciauskas-bgse** [comment]
Completed
